name: pinjam_in
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ^3.8.1

dependencies:
    flutter:
        sdk: flutter
    flutter_svg: ^2.0.7
    google_fonts: ^6.3.2
    provider: ^6.1.1
    cached_network_image: ^3.2.3
    flutter_contacts: ^1.1.9+2
    url_launcher: ^6.1.14
    file_picker: ^10.3.3
    image_picker: ^1.1.1
    image: ^4.0.17
    path_provider: ^2.0.13
    shared_preferences: ^2.1.1
    supabase_flutter: ^2.10.3
    flutter_dotenv: ^6.0.0
    http: ^1.5.0
    uuid: ^4.5.1
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - .env
